import type { Metadata } from "next";
import Navigation from "../components/ui/Navigation"
import "./globals.css";
import "../style/style.css"
import {CartProvider} from "../Context/CartContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
    <html lang="en">
      <html lang="en"></html>
      <body>
        <Navigation/>
        <main>
        {children}
        </main>
      </body>
    </html>
    </CartProvider>
  );
}
